import type { Icon, IconWeight } from "@phosphor-icons/react";
import {
  ArrowCircleRightIcon,
  ArrowsLeftRightIcon,
  ArticleIcon,
  CalendarCheckIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CheckCircleIcon,
  CheckIcon,
  ClockIcon,
  CompassToolIcon,
  CreditCardIcon,
  CubeIcon,
  EyeIcon,
  FileArrowUpIcon,
  FileIcon,
  FileMagnifyingGlassIcon,
  FileTextIcon,
  FileXIcon,
  FilesIcon,
  FlagIcon,
  FolderOpenIcon,
  FolderPlusIcon,
  HandshakeIcon,
  HourglassIcon,
  HourglassMediumIcon,
  InfoIcon,
  InvoiceIcon,
  MapPinIcon,
  PackageIcon,
  PencilRulerIcon,
  PulseIcon,
  ReceiptIcon,
  RobotIcon,
  SealCheckIcon,
  ShieldCheckIcon,
  ToolboxIcon,
  UserIcon,
  WalletIcon,
  WarningCircleIcon,
  WarningIcon,
  WrenchIcon,
  XCircleIcon,
} from "@phosphor-icons/react";

const icons: Record<string, Icon> = {
  activity: PulseIcon,
  alert: WarningIcon,
  arrowRight: ArrowCircleRightIcon,
  badgeCheck: SealCheckIcon,
  bot: RobotIcon,
  box: CubeIcon,
  calendar: CalendarCheckIcon,
  card: CreditCardIcon,
  check: CheckIcon,
  checkCircle: CheckCircleIcon,
  chevronLeft: CaretLeftIcon,
  chevronRight: CaretRightIcon,
  clock: ClockIcon,
  compass: CompassToolIcon,
  creditCard: CreditCardIcon,
  documentEye: FileMagnifyingGlassIcon,
  expand: ArrowsLeftRightIcon,
  eye: EyeIcon,
  file: FileTextIcon,
  fileCheck: ArticleIcon,
  fileUp: FileArrowUpIcon,
  fileWarning: FileXIcon,
  files: FilesIcon,
  flag: FlagIcon,
  folderCheck: FolderOpenIcon,
  folderPlus: FolderPlusIcon,
  handover: HandshakeIcon,
  handshake: HandshakeIcon,
  info: InfoIcon,
  packageCheck: PackageIcon,
  pin: MapPinIcon,
  plan: PencilRulerIcon,
  quote: InvoiceIcon,
  receipt: ReceiptIcon,
  ruler: PencilRulerIcon,
  shield: ShieldCheckIcon,
  solar: ToolboxIcon,
  tool: WrenchIcon,
  truck: PackageIcon,
  user: UserIcon,
  wait: HourglassIcon,
  waitBadge: HourglassMediumIcon,
  warningCircle: WarningCircleIcon,
  walk: ArrowCircleRightIcon,
  wallet: WalletIcon,
  x: XCircleIcon,
};

export default function StageIcon({
  name,
  className = "h-4 w-4",
  weight = "fill",
}: {
  name: string;
  className?: string;
  weight?: IconWeight;
}) {
  const IconComponent = icons[name] || FileIcon;

  return <IconComponent className={className} weight={weight} aria-hidden="true" />;
}
